### ISSUE TITLE
so cool

### ISSUE THREAD

**Issue by TonyChenn** [gilzoide/unity-objectivec#1]
such a cool tool, why not maintain it?

**Comment by gilzoide** [comment]
> such a cool tool

Right? I also like it =]

> why not maintain it?

1. To be honest, there's little I would add to this package. Mostly better block support, which is not an easy task (the ABI is quite complex, the Objective-C compiler is the one that solves this tricky ABI stuff). Maybe builtin support for NSMutableArray and NSMutableDictionary subscript operator for setting values, and that's all I can remember 🤔
2. It's easy enough adding Objective-C/Objective-C++ files to a Unity project and calling native functions with C#'s P/Invoke, so this project is not reeeally necessary. But it's rad that it's possible to use only C# to call arbitrary Objective-C stuff xD
3. I have lots of other projects to maintain, so given that there's not much to add, and I'm not really using this myself, it is far down in my priority list.

If you like the package and want to contribute/maintain it, I'd be glad to help! Maybe we can make this tool even better =D

I'm closing this issue now. If you have problems with the package, or suggestions about what could be better, open new issues or discussions about them. Cheers \o/
